### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by jonaslorander** [madskristensen/MiniBlog#156]
Hi,

`string extension = Regex.Match(match.Value, "data:([^/]+)/([a-z]+);base64").Groups[2].Value;`

This regex is only usable for images, and not other type of file. For instance, it will match `plain` for txt-files, and for zip-files the mime-type is application/x-zip-compressed, and x-zip-compressed will match as `null`. Word and Excel files will also be matched as `null` causing the extension to be `.bin`.

A solution for this would be to look for the filename in the link that is created, and get the real extension. It would also be possible to have a more human readable this way and saving the uploaded files as `guid_filename.ext`.

Does anyone have anything done on this already, or planing to?

**Comment by jonaslorander** [comment]
This seems to do the trick:
```
    private void SaveFilesToDisk(Post post)
    {
        foreach (Match match in Regex.Matches(post.Content, "(src|href)=\"(data:([^\"]+))\"(>.*?</a>)?"))
        {
            string extension = string.Empty;
            string filename = string.Empty;

            // Image
            if( match.Groups[1].Value == "src" )
            {
                extension = Regex.Match(match.Value, "data:([^/]+)/([a-z]+);base64").Groups[2].Value;
            }
            // Other file type
            else
            {
                // Filename
                extension = Regex.Match(match.Value, "data:([^/]+)/([a-z0-9+-.]+);base64.*\">(.*)</a>").Groups[3].Value;
            }

            byte[] bytes = ConvertToBytes(match.Groups[2].Value);
            string path = Blog.SaveFileToDisk(bytes, extension);

            string value = string.Format("src=\"{0}\" alt=\"\" ", path);

            if (match.Groups[1].Value == "href")
                value = string.Format("href=\"{0}\"", path);

            Match m = Regex.Match(match.Value, "(src|href)=\"(data:([^\"]+))\"");
            post.Content = post.Content.Replace(m.Value, value);
        }
    }
```
Perhaps there is a better way to do it?

File names become `guid.filename.ext`.

**Comment by madskristensen** [comment]
Awesome! Wanna send it as a PR?

**Comment by jonaslorander** [comment]
Sure can! #157
