### ISSUE TITLE
Maybe point to Windows Live Writer 2012 instead of the old 2009 version?

### ISSUE THREAD

**Issue by teamaton** [madskristensen/MiniBlog#158]
Hi Mads,

I'm glad I've run into MiniBlog because I was looking for a light-weight ASP.NET blog engine with WLW support :-)

When I read the README I noticed you mentioned WLW build 14.0.8117.416 which made me wonder which version I'm using - and it turns out I have 16.4.3528.331:

![wlw-2012](https://cloud.githubusercontent.com/assets/181005/5984233/a43c08e0-a8d4-11e4-9872-a1ec53ab593f.png)

I then noticed your dowload link and found that it points to the 2009 version:
![wlw-dl-2009](https://cloud.githubusercontent.com/assets/181005/5984276/02fb50c0-a8d5-11e4-9416-a971c468088f.png)

Just the other day I found Hanselman's post [Download Windows Live Writer 2012](http://www.hanselman.com/blog/downloadwindowslivewriter2012.aspx) which is nothing more than a highly ranked link to the WLW 2012 download page.

I suggest you update your installation and the README to that version and the new download link if you don't mind logging into microsoft.com.

**Comment by RandomlyKnighted** [comment]
@madskristensen This can be closed now :smile:
