### ISSUE TITLE
Status code 200, Content -length = 0 (blank page)

### ISSUE THREAD

**Issue by MarkDalsaso** [madskristensen/MiniBlog#165]
New to Razor Web Pages (and GitHub). I've been successful testing MiniBlog in IIS Express; both as a stand-alone, as well as a virtual app. ("http://localhost:12345" and "http://localhost:12345/blog"). When I deploy to my hosting provider all I get is a blank page. I have tried deploying to a sub-domain (blog.mydomain.com) as well as virtual app. (www.mydomain.com/blog).

I feel like I'm missing something obvious. Is anyone else seeing this behavior?

**Comment by programcsharp** [comment]
Could this be related to #153?

If it's working locally, it may not be the same issue -- but the symptom is similar.

**Comment by programcsharp** [comment]
Another thing to check is whether your hoster has the IIS UrlRewrite module (http://www.iis.net/downloads/microsoft/url-rewrite) installed and enabled. MiniBlog makes heavy use of that for inbound url rewriting.

**Comment by MarkDalsaso** [comment]
Thx Chris for the speedy reply. Originally I thought it was related to the malformed html (#153). It does work locally and I even tried removing all the posts in an effort to get index.cshtml to render. Still nothing.

I checked with my hosting company (SmarterASP.NET) and they do support URL Rewrite 2.0. They're not being especially helpful with this; they're giving me the old "don't support 3rd party app's..your on your own"! I do so much better debugging ASP.NET MVC....totally frustrated with this!

Does anyone have any debugging/troubleshooting ideas/tips? FYI: I can access IIS via IIS Manager remote.

**Comment by jonaslorander** [comment]
I'm in the same situation with my host. But my problem was with more then the UrlRewrite; I hade to revert all the way back to MVC 3! Regarding UrlRewriting, my host olny allows http://urlrewriter.net/ to be used, so I had to rewrite the Web.config file to be using that instead.

**Comment by MarkDalsaso** [comment]
My provider claims to have URL Rewrite 2.0, I'm not sure how I would go about verifying that. If any one wants to take a look see...please, by all means! http://testblog.durangobpa.com/

The only thing I've changed from the master was in the Web.config; the credentials node (user name and password). I'm at my wits end.

**Comment by MarkDalsaso** [comment]
About the only thing I can get to work is the custom 404. Note: 
http://testblog.durangobpa.com/kj    ... throws IIS standard 404
and    http://testblog.durangobpa.com/post/boo  ...throws custom 404.cshtml

**Comment by MarkDalsaso** [comment]
Okay, so I've turned off dynamic compression and now it's working. Does this make sense to anyone?
Changed:
    <urlCompression doDynamicCompression="true" doStaticCompression="true"/>
To:
    <urlCompression doDynamicCompression="false" doStaticCompression="true"/>

**Comment by programcsharp** [comment]
That's interesting. Looks like its a known issue, sort of:
https://duckduckgo.com/?q=iis+dynamic+compression+blank+page -- I see
reports of the same thing, but no reason or solution other than turning off
dynamic compression.

**Comment by MarkDalsaso** [comment]
Yes, I'm stumped. Just to be clear, (looks like the editor filtered out some syntax), in system.webServer I changed urlCompression doDynamicCompression="true" to urlCompression doDynamicCompression="false"

Hopefully this will help someone else down the road...my brain vein was pumping so hard it red lined.

**Comment by forwardshapes** [comment]
@MarkDalsaso HUGE thanks to you for this. I recently migrated my MiniBlog to SmarterASP.net and couldn't figure out why it wouldn't load. Your solution fixed it for me. Thanks again!!

**Comment by MarkDalsaso** [comment]
Cool!
