### ISSUE TITLE
Picture upload not supported by blog

### ISSUE THREAD

**Issue by 0liver** [madskristensen/MiniBlog#168]
I'm having trouble with posting my first to my MiniBlog instance - I'm getting this (unfortunately, German) dialog

![wlw-picture-upload-not-supported](https://cloud.githubusercontent.com/assets/164360/6472643/3efad158-c1f4-11e4-8ab6-1650966919fe.png)

Here's an English version of the same dialog which I found on the net:
![livewriterwperror 1](https://cloud.githubusercontent.com/assets/164360/6472620/1ee7fc24-c1f4-11e4-92f0-b9075e899c20.png)

Could you point me in a direction why this could be happening? I've already given full file access permissions to IIS_IUSRS to no avail.

**Comment by russcam** [comment]
I was getting the same issue after overwriting the old application directory on the web server with a new version. Be sure that  IIS_IUSRS has read and write access to ~/posts and ~/posts/files, the latter being where images will be written.

**Comment by 0liver** [comment]
@russcam: Thank you so much! This solved my problem in an instant :-)

**Comment by 0liver** [comment]
@russcam: Thank you very much, this was indeed the problem: I had deleted the `~/posts/files` folder!

**Comment by russcam** [comment]
No worries, glad it helped!
