### ISSUE TITLE
FeedHandler.cs does not check ispublished flag

### ISSUE THREAD

**Issue by MarkDalsaso** [madskristensen/MiniBlog#172]
I don't know no enough about ATOM feeds to say whether or not this is actually a problem. The feed handler (FeedHandler.cs) doesn't check the ispublished boolean value, so all posts, (even ones with ispublished = false) get included in the ATOM feed xml.

Is this by design?

**Comment by MarkDalsaso** [comment]
Okay, so maybe a dumb question. Anyway, added simple 'if' check to GetItems() method of FeedHandler.cs...
    private IEnumerable<SyndicationItem> GetItems()
    {
        foreach (Post p in Blog.GetPosts(10))
        {
            // Note: MRD 4/22/15 inserted this "if" to keep unpublished posts out of Atom feed xml (URL: '<host or domain>/blog/feed/*' )
            if (p.IsPublished)
            {
                var item = new SyndicationItem(p.Title, p.Content, p.AbsoluteUrl, p.AbsoluteUrl.ToString(), p.LastModified)
                {
                    PublishDate = p.PubDate
                };

                if (!string.IsNullOrWhiteSpace(p.Excerpt))
                    item.Summary = new TextSyndicationContent(p.Excerpt);

                item.Authors.Add(new SyndicationPerson("", p.Author, ""));
                yield return item;
            }
        }
    }

**Comment by sam-ward** [comment]
If no-one else does, I will have a look at this on the weekend (if not
before) as I thought I had previously fixed this (I am unable to check from
the office at the moment).

Cheers
Sam

**Comment by MarkDalsaso** [comment]
Okay, thanks Sam. As I mentioned, wrapping the guts of the GetItems() method inside the p.IsPublished condition block seems like the obvious fix. I tested it and it works for me.

**Comment by sam-ward** [comment]
So I have had a look and I hadn't previously fixed it (that was the sitemap.xml I was thinking of). But between your original post and now, Andrei Dzimchuk made a commit (fc01867d8d2426e5bdea490e03d3d86df03d1407) that modifies the behaviour of Blog.GetPosts() to take into account whether the post is published (or if you're an admin). The net result is that the feeds should now only display published posts (unless your an admin, in which case it will display the 10 most recent posts).

(I have also just created a pull request to make the same change to the sitemap.cshtml)

**Comment by RandomlyKnighted** [comment]
I just tested this out using the latest code from the repository. The commits made by @dzimchuk and @sam-ward fixed the issue.

@madskristensen can you close this please?

**Comment by MarkDalsaso** [comment]
Cool!
