### ISSUE TITLE
Entering Content

### ISSUE THREAD

**Issue by lenyct** [madskristensen/MiniBlog#176]
I tried doing a test post from both IE and Chrome and the content wasn't entering,

It just underlined the text already in the content text box that's already there when loaded.

**Comment by RandomlyKnighted** [comment]
I can confirm this bug a well, but haven't had a chance to debug the project to figure out what is causing the issue. I have tested using IE 11, Firefox 37.0.1, and Chrome 41.0.2272.118.

**Comment by RandomlyKnighted** [comment]
@lenyct try it again with the latest version of the editor. The version I had uploaded previously was the incorrect version so this one should fix your issues.
