### ISSUE TITLE
Deploy to Azure doesn't work

### ISSUE THREAD

**Issue by andrewmatveychuk** [madskristensen/MiniBlog#191]
It seems that Deploy to Azure feature does not work. While trying to use the button I got the following error at deploy.azure.com website:
![error](https://cloud.githubusercontent.com/assets/12231656/7471811/1dd81a78-f334-11e4-82fb-3bcc1a6e4852.png)

**Comment by madskristensen** [comment]
This is a problem with the "Deploy to Azure" button feature which isn't part of MiniBlog. 

@davidebbo, any ideas?

**Comment by davidebbo** [comment]
Works fine for me. Are you still seeing this? What happens if you just navigate to https://deploy.azure.com/?

If you still have an issue, please open one on https://github.com/projectkudu/slingshot. @madskristensen you can probably close this one here.

**Comment by andrewmatveychuk** [comment]
@davidebbo  The deploy.azure.com website is working fine without any noticeable issues.
Does this deployment option require a configuration file like 'deploytoazure.json' in a repository (http://www.bradygaster.com/post/the-deploy-to-azure-button)?

**Comment by davidebbo** [comment]
No, that is optional. So you're saying that you can go to https://deploy.azure.com/, but that if you go to https://github.com/madskristensen/MiniBlog and click the button in doesn't work?

**Comment by andrewmatveychuk** [comment]
@davidebbo Yes, you a right. After the error message nothing happens.
![deploytoazure-error](https://cloud.githubusercontent.com/assets/12231656/7481076/10c3dfe2-f376-11e4-8ec7-7609a8f70215.png)

**Comment by davidebbo** [comment]
To isolate whether it's related to MiniBlog, please try going to https://github.com/Tuesdaysgreen/HelloWorlddemo and click the button. Does it fail in this case as well or does it work?

**Comment by andrewmatveychuk** [comment]
Got the same error. For now I have only a DreamSpark subscription activated in my Azure account. Could this issue be related to subscription limitations?

**Comment by davidebbo** [comment]
Can you please open an issue on https://github.com/projectkudu/slingshot? That will be a better place to track it. Thanks!

**Comment by andrewmatveychuk** [comment]
The issue reopened at https://github.com/projectkudu/slingshot/issues/46

**Comment by davidebbo** [comment]
This now works fine.
