### ISSUE TITLE
WLW on Windows 10?

### ISSUE THREAD

**Issue by bdelaney** [madskristensen/MiniBlog#202]
I note that a few issues concern LiveWriter.
Is this editor even going to be supported on Windows 10?
I'm running the most recent build, 10130, and I'm not able to install LiveWriter.
And doesn't this seem like the end of the line for good old LiveWriter?
Anyone have other suggestions for a blogging editor that works well with MiniBlog?

**Comment by JDunaganFL** [comment]
I understand some folks at Microsoft are working to get it open-sourced. WLW has quite a following.

 

Anyway, I’d at least wait for Windows 10 before I pulled the plug.

**Comment by cmatskas** [comment]
Hi @bdelaney, I had a chat with Scott Hanselman a few weeks back and I can attest that WLW is going open source and that it should be available soon. As soon as the source code is out, I'm sure a W8.1/w10 app will be released. I'm actually one of the people interested in building one. In the meantime, you'll have to make do with what's available. I hope this helps and that you can find a work around the current issues you're experiencing on W10

**Comment by bdelaney** [comment]
I know he is a fan of WLW. Be great to see WLW get a second life and be OSS to make the plugins viable too.
