### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by bdelaney** [madskristensen/MiniBlog#204]
The feature for optimizing images is not working in my test installs. I've tried both PNG and JPG files.

Also, when posts are deleted, is it feasible to delete the image(s) at the same time? With the guid inside the post xml, the file may be parsed and deleted, right?

**Comment by madskristensen** [comment]
Right. The Yahoo API this feature uses are no longer operational. The code (Nuget package and C# code) should be removed. Wanna send a pull request?

**Comment by madskristensen** [comment]
This is fixed by pull request #200
