### ISSUE TITLE
madskristensen.net rogue script!

### ISSUE THREAD

**Issue by styfle** [madskristensen/MiniBlog#206]
@madskristensen 
This is probably not the proper place to post but...

I can't access http://madskristensen.net because there (what looks like) a rogue script: http://google-analytics.com.m82.be/analytics.js that is being (rightly?) blocked.

Is this intentional?

**Comment by sam-ward** [comment]
Hi Steven,

Assuming you are referring to .m82.be part of the URL.  This is Mads
private CDN that is part of his MiniBlog deployment (and is as intended).

See https://github.com/madskristensen/ReverseProxyCDN for more info on the
CDN.


Cheers
Sam

**Comment by styfle** [comment]
Hi Sam,

My workplace was blocking it and the URL looked sketchy so I assumed the worst.
Thanks for clearing that up.
That reverse proxy looks interesting as well.
I'll close this :dog:
