### ISSUE TITLE
MiniBlog Attribution

### ISSUE THREAD

**Issue by teabaggs** [madskristensen/MiniBlog#208]
Hi Mads,

I would like to change the attribution at the bottom of the blog page from 

`<span>Copyright © 2015 <a href="http://madskristensen.net" itemprop="url name">Mads Kristensen</a></span>`

to

`<span>Copyright © 2015 My Company.</span><span>MiniBlog engine courtesy of <a href="http://madskristensen.net" itemprop="url name">Mads Kristensen</a></span>`

I feel like the Copyright Mads Kristensen will be confusing to readers who may assume the content is yours. As this blog will go on a site that sells copyright content I want to avoid this confusion at all costs. Would you be cool with this?

**Comment by RandomlyKnighted** [comment]
You can always change it on your fork before uploading it to your website.

**Comment by madskristensen** [comment]
@teabaggs of course
