### ISSUE TITLE
Concerns with Miniblog

### ISSUE THREAD

**Issue by kershnerd** [madskristensen/MiniBlog#212]
I really want to use this but I have a few concerns.

This uses XML for storing blogs and comments.  How would this work/scale if it was on Azure and there were several web servers serving the website (server farm)?

I really need the ability for an optional intro image.  In my application (actually most blogs do this), there needs to be an intro image.  I have looked into adding this to the post model but I am a little bit confused on how to implement the upload and save to disk (functions that are already there).  I could look implementing this issue if I was sure there was a solution to the first issue.

**Comment by RandomlyKnighted** [comment]
Miniblog works well with Azure. In fact I know there are several people myself included who host their blog on Azure.

**Comment by kershnerd** [comment]
I have it working on azure as well.  My concern is that if you scale to 2 front end servers, the XML file based backend breaks.

**Comment by asapostolov** [comment]
It doesn't break. Azure replicates the files of each Web server or uses the same file system for both web servers so any change in a file in one of the servers will be replicated across the others.

**Comment by madskristensen** [comment]
@kershnerd  Is this an observed issue or are you fearing that it will break if you try?

Azure Websites uses the same file system under the hood even when scaling to multiple servers.

**Comment by kershnerd** [comment]
Just an assumption... I assumed that when azure scales, the server that is handling my new blog post will have a different version of the XML that might be serving some of the traffic.  If this is not how this works then this is great news.  Let me know and I will close this thread.

Thanks....
