### ISSUE TITLE
Add new cshtml razor page to site

### ISSUE THREAD

**Issue by claudefox** [madskristensen/MiniBlog#214]
Seemingly there's no way in the current project to add a new CSHTML page?  Probably because it's been streamlined but what DLLs do I add back to regain this functionality.

**Comment by fredrikeriksson** [comment]
Can't you just copy an existing .cshtml and then rename it?

**Comment by claudefox** [comment]
Yep, I actually did that but was wondering if there was a better way.  If everyone is doing it that way with this app, I guess I'll do it the same way.  

I'm actually integrating it with my whole website and application.
