### ISSUE TITLE
demo home page not coming up on your demo site

### ISSUE THREAD

**Issue by claudefox** [madskristensen/MiniBlog#225]
I feel a little bad because this is possibly my fault.  I was trying to get videos to re-size responsively in a div in the raw HTML on your demo site.  I did something wrong and as soon as I did the default page is blank.  This was several weeks ago.

I also think this because other pages still work fine.

Sorry about that...

**Comment by claudefox** [comment]
Also, I tried to get back in to fix it but was not able to.

**Comment by RandomlyKnighted** [comment]
I [don't see any commits](https://github.com/madskristensen/MiniBlog/commits/master) made by you. So I don't see how you could have done something to the page.

**Comment by claudefox** [comment]
http://miniblog.azurewebsites.net/

comes up blank.  I believe this is because of the code I put into a blog article on that site.

**Comment by madskristensen** [comment]
Redeploying...

**Comment by madskristensen** [comment]
Fixed
