### ISSUE TITLE
Posts are not saving to file system when running on azure app service.

### ISSUE THREAD

**Issue by darrenshrwd** [madskristensen/MiniBlog#233]
I can create a new blog post and see the content via the website, however if I restart the website the post is gone.

-I have confirmed that there are no xml files getting created via kudu and ftp.  There is no error thrown it seems though.
-When running locally under IIS express the xml file is created.  I can create xml files locally and publish them.

(I have the blog hosted in virtual app under /blog)

**Comment by darrenshrwd** [comment]
The issue was I had turned on local cache (and not thought of this impact):
https://azure.microsoft.com/en-us/documentation/articles/app-service-local-cache/

Would be nice to be able to have both, but then I guess I need a separate site for the blog rather than a virtual application.  Anyway nothing to do with miniblog, azure specific.

**Comment by RandomlyKnighted** [comment]
Thanks for posting your solution. That may have been what I was doing wrong on my blog back when I was using this.
