### ISSUE TITLE
Scale video to mobile size?

### ISSUE THREAD

**Issue by claudefox** [madskristensen/MiniBlog#234]
I see that pictures scales properly in a post when viewed in a mobile device.

I would like to do the same with videos.  I have posted a video here on the demo site:
http://miniblog.azurewebsites.net/post/test-videoz?mode=edit

The HTML code has an embeded link to a  youtube video that I would just like to scale on a mobile device.

Any ideas??

**Comment by RandomlyKnighted** [comment]
@claudefox scaling the pictures is actually done via the editor itself. MiniBlog uses the [bootstrap-wysiwyg] editor. I just created a new issue in that repo so you can keep track of it's progress.

**Comment by claudefox** [comment]
<style>@media screen and (min-device-width:240px) and (max-device-width:480px){.video1{min-height:350px !important;max-width:420px !important;display:none !important}}</style><iframe src="https://www.youtube.com/embed/rCnRqZw4WiE" allowfullscreen="" width="100%" height="315" frameborder="0"></iframe>
