### ISSUE TITLE
Support Keywords/Tags

### ISSUE THREAD

**Issue by phatcher** [madskristensen/MiniBlog#239]
@maads Would supporting keywords/tags be outside the core scope - I'd split out the implementation a bit more if I'm contributing it back to the main code line

**Comment by RandomlyKnighted** [comment]
I believe you meant to tag @madskristensen.

**Comment by madskristensen** [comment]
That is out of scope. You can use "categories" as tags. There is no reason to have both. Old blog systems have it, but it has little to no practical use
